#!/usr/bin/env python
import sys
sys.path.insert(0, '/Users/allenwang/workspace/Python/codeComber')
# sys.path.insert(0, '/usr/local/codeComber')
import engine

if __name__ == "__main__":
    eng = engine.Engine()
    eng.run()
